name: docs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          sudo apt install pandoc
          pip install .[dev]
      - name: Sphinx build html documentation
        run: |
          sphinx-build -b html -t locales_en docs/source docs/build/html/en
          sphinx-build -b html -t locales_fr docs/source docs/build/html/fr
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }} 
        with:
          publish_branch: gh-pages-docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true